# Site settings
title: TechStuff
email: harish207@live.com
description: > # this means to ignore newlines until "baseurl:"
 Hi, and welcome to my tech blog. I am Harish, and I share my views on some cool techstuff here.
 If you were looking for my other blog or my homepage, or to contact me, look at the Contact page.
baseurl: "/tech" # the subpath of your site, e.g. /blog/
url: "http://harishv7.github.io" # the base hostname & protocol for your site
twitter_username: Harish__V
github_username:  harishv7

# Build settings
markdown: kramdown
